### ISSUE TITLE
changes needed to NOBA input files for new fishing implementation

### ISSUE THREAD

**Issue by gavinfay** [thefaylab/hydra_sim#16]
examples in the repo, but these need incorporating into the auto-generated files from atlantisOM.

All references to Nfleet in all three files should be changed to 1 (single fleet).

`hydra_sim_NOBA.dat`   [same place as previous, different data structure]
\# indicator_fishery_q(1,Nareas,1,Nfleets,1,Nspecies)
\# which species represent targeted catch. These are used to estimate exploitation rate in assessment
1 1 1 1 0 1 1 1 0 1 1

`hydra_sim_NOBA.pin`. [after recsigma]
\# Fishing mortality
\# Average F by fleet and area
\# init_matrix avg_F(1,Nareas,1,Nfleets,avg_F_phase)
-1.6
\# Annual F deviations
\#init_3darray F_devs(1,Nareas,1,Nfleets,1,Nyrs,dev_F_phase)
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
\# Fishery qs
\#  init_vector ln_fishery_q(1,Nqpars) (= sum of fishery_indicator_q - Nfleet*Narea)
0 0 0 0 0 0 0 0

`hydra_sim_NOBA-ts.dat`
Catches from species not caught in the fishery can be removed from the file.
Also remove catch at size comp rows for these species (though GF can build in a trap for this)

**Comment by sgaichas** [comment]
I have updated [generating code](https://github.com/ices-eg/wg_WGSAM/blob/master/SkillAssessment/SkillAssessProject.Rmd)  and [hydradata](https://github.com/thefaylab/hydradata/blob/master/R/create_datpin_files.R) to have a single fleet and to write the indicator_fishery_q in the `.dat` file. I have not yet pushed a new dat file to hydra_sim because I need to make sure I preserve the other changes in it since it was last generated.

I have updated [generating code](https://github.com/ices-eg/wg_WGSAM/blob/master/SkillAssessment/SkillAssessProject.Rmd) to remove unfished species from the catch in the `-ts.dat` file and corrected species numbering in [hydradata](https://github.com/thefaylab/hydradata/blob/master/data-raw/create_RData_NOBA.R) so that the catch at length file has correct species numbers (*they were wrong before because catch at length doesn't have unfished species 5 and 9*). 

However, in checking the `-ts.dat` output I found that catch at length data starts one year before catch data (year 15 vs 16). So far I can't see that the generating code is mis-assigning years, but I am still testing and also may need to check the Atlantis inputs. I want to figure this out before pushing the new `-ts.dat`.

Adding F and Fdevs info to the `.pin` file is still in progress...

**Comment by sgaichas** [comment]
the `.dat` file should be good to go now 5154b2f88ceed0fee6ddcc9d0426b76f1a233821

the `-ts.dat` posted here removes unfished species from catch, corrects species numbering for catch at length, and caps inpN at 1000 for length data. it **still has the problem of mismatched years described above**; digging into that now. 2888c25191d636e2fef580ecbd71fa8f6f858fc3

**Comment by gavinfay** [comment]
Thank you Sarah!

**Comment by gavinfay** [comment]
These changes have introduced an error in the `.dat` file. 
`fleetMembers` should be length `numGuilds` (here 11) not `nfleets`.
So:
```
#Fleet Membership fleetMembers(1,numGuilds)
  1 1 1 1 1 1 1 1 1 1 1
```
Thanks @MaC-Perez for catching this!

**Comment by sgaichas** [comment]
Nice catch! (haha) fixed in `hydradata` with https://github.com/thefaylab/hydradata/commit/466b0c55fa578f72e4e4fccc6018d2effbb07521

Would you like me to regenerate a .dat file or just fix manually for now?

**Comment by sgaichas** [comment]
These changes and corrections are now automated in `hydradata` so I'm marking as complete.
